logseq/mldoc

lib/syntax/inline.ml

see also https://github.com/logseq/logseq/issues/827

Fix: uri parsing use package 'uri'

---

lib/parsers.ml
lib/syntax/drawer.ml
test/test_markdown.ml

Related to https://github.com/logseq/logseq/issues/1390
Tested on my local-built web app.

fix(markdown): properties end with carriage-return

---

lib/prelude.ml
lib/syntax/inline.ml

Uri.Parser.uri_reference is slow

Don't use 'uri' to parse

---

lib/syntax/footnote.ml
lib/syntax/markdown_definition.ml
test/test_markdown.ml
test/test_org.ml

related https://github.com/logseq/logseq/issues/1405

fix: escape char wrongly

---

lib/export/markdown.ml

- remove `(())` between block-references
- recalculate indent level for embed pages or block

update export style

---

lib/export/markdown.ml

if embed-page(or block) is the only member of the heading, then
replace this heading by the embed-page(or block).

enhance(md): update export embed-page(or block) style

---

lib/export/markdown.ml
lib/syntax/inline.ml

feat: add inline html support

---

lib/document.ml
lib/syntax/inline.ml
lib/syntax/timestamp.ml
lib/syntax/type.ml

fix https://github.com/logseq/logseq/issues/1541

Add default value for option type when unmarshal json

---

lib/syntax/inline.ml
test/test_markdown.ml

support link-syntax like this:  `[link]([[page name]])`

support page-refs in link url part

---

lib/parsers.ml
lib/syntax/extended/hash_tag.ml
test/test_markdown.ml

fix: tag parser ignore last consecutive periods

---

lib/option.ml
lib/parsers.ml
lib/syntax/inline.ml
test/test_markdown.ml

fix(md): emphasis syntax issues

---

lib/mldoc_parser.ml
lib/syntax/drawer.ml
lib/syntax/markdown_property.ml
test/test_markdown.ml

add md simplified-property syntax: 
`key::value`

feat(md): add simplified-property-syntax

---

mldoc.opam
test/dune
test/gen_md_files.ml

usage:
```
dune build test/gen_md_files.exe 
./_build/default/test/gen_md_files.exe <page_num>
```

Feat: add gen_md_files

---

lib/prelude.ml
lib/syntax/lists.ml
test/test_markdown.ml

fix: heading in list

---

bench/bench.ml
bin/main.ml
js/lib.ml
lib/dune
lib/export/conf.ml
lib/export/exporter.ml
lib/export/markdown.ml
lib/export/opml.ml
lib/export/reference.ml
lib/option.ml
lib/syntax/tree_type.ml
lib/zip.ml
mldoc.opam
test/dune
test/test_markdown.ml
test/test_org.ml
test/test_zip.ml

opml export

---

lib/parsers.ml
test/gen_md_files.ml

usage:
```
dune build test/gen_md_files.exe
../_build/default/test/gen_md_files.exe <page-num> <dir-num>
```

enhance(gen_md_files): generate random pagename & dirname

---

lib/syntax/heading.ml
test/test_markdown.ml

related to issues： https://github.com/logseq/logseq/issues/2247 ， https://github.com/logseq/logseq/issues/2239 ， https://github.com/logseq/logseq/issues/2227

fix: parse error on "- #tag"

---

lib/syntax/tree_type.ml
lib/syntax/tree_type.mli
lib/syntax/type_op.ml
lib/transform/transformer.ml
test/dune
test/test_export_markdown.ml

```
- ref-text
id:: 60d2fbb9-9fc1-4a3d-b169-13045b7203be
- aaa ((60d2fbb9-9fc1-4a3d-b169-13045b7203be)) bbb
```
exported md(before):
```
- ref-text
- aaa 
ref-text
bbb
```
after:
```
- ref-text
- aaa ref-text bbb
```

fix: update exported md format

---

lib/syntax/drawer.ml
test/test_markdown.ml
test/test_org.ml

see also https://github.com/logseq/logseq/issues/2286

enhance: merge normal properties & hashmark properties

---

lib/syntax/inline.ml
test/test_markdown.ml

fix: markdown image link

---

lib/opml_parser.ml
lib/syntax/block0.ml
lib/transform/markdown_transformer.ml

fix import opml failed from mubu

enhance: support &nbsp in xml attr

---

lib/syntax/heading0.ml
lib/syntax/inline.ml
lib/syntax/type_parser.ml
test/test_markdown.ml

support link syntax: `[label](<u r l>)`

enhance: support link url contains spaces

---

lib/syntax/inline.ml
test/test_org.ml

fix: org link label

---

lib/syntax/inline.ml
test/test_org.ml

fix invalid org-link & org-nest-link

fix(orgmode): link & nestlink

---

lib/export/html.ml
lib/export/markdown.ml
lib/syntax/tree_type.ml
lib/syntax/type_op.ml
lib/util.ml
test/test_export_markdown.ml
test/test_export_opml.ml
test/test_markdown.ml

related to https://github.com/logseq/logseq/issues/3019

fix(export): keep md-heading when export-md

---

lib/export/html.ml
lib/syntax/block0.ml
lib/syntax/inline.ml
lib/syntax/type_op.ml

quick parsing-path for e.g. embed base64 image link

add embed_data link type

---

lib/syntax/tree_type.ml

usually caused by recursive refs.
fix https://github.com/logseq/logseq/issues/3578

fix(export): ignore replace embed blocks when too deep

---

lib/export/markdown.ml
lib/syntax/block0.ml
lib/syntax/heading0.ml

fix: keep properties when exporting
