logseq/mldoc

lib/syntax/inline.ml
test/test_markdown.ml

Inline code has higher precedence than any other inline constructs except HTML tags and autolinks(quicklinks)

fix(markdown): inline code has high precedence

---

lib/parsers.ml
lib/syntax/markdown_code_block.ml
test/test_markdown.ml
test/test_org.ml

related to https://github.com/logseq/logseq/issues/1438

fix(markdown): multiple-line quote&example isn't correctly displayed

---

lib/syntax/inline.ml
test/test_markdown.ml

parse `{{macro [[foo,bar]]}}` into `Macro {name="macro", args=["[[foo,bar]]"]}`,
instead of breaking `[[foo,bar]]` into `["[[foo";"bar]]"]`

enhance: macro args parsing

---

lib/parsers.ml
lib/syntax/inline.ml
test/test_markdown.ml

- parse balanced parentheses in inline-link & link
- remove some autolink's delimiters
- allow page-ref syntax in link's label part
- inline-link will exclude ending period [ ','; ';'; '.'; '!'; '?' ]

fix: update link parser

---

lib/syntax/inline.ml
test/test_markdown.ml

related to https://github.com/logseq/logseq/issues/1546

fix: page-ref before markdown-link

---

lib/syntax/inline.ml
test/test_org.ml

fix org-mode emphasis syntax issues similar to md.

fix(org): emphasis syntax issues

---

lib/document.ml
lib/syntax/heading.ml
lib/syntax/type.ml
test/test_markdown.ml

Added new field `size: int option` to `Heading`.
example: `"- ##"`
-> 
```
Type.Heading
{ Type.title = []
; tags = []
; marker = None
; level = 1
; numbering = None
; priority = None
; anchor = ""
; meta = { Type.timestamps = []; properties = [] }
; unordered = true
; size = Some 2
}
```

feat: support `- ##` like heading

---

lib/export/html.ml
lib/export/markdown.ml
lib/syntax/extended/hash_tag.ml
lib/syntax/extended/nested_link.ml
lib/syntax/heading.ml
lib/syntax/inline.ml
lib/syntax/tree_type.ml
lib/syntax/type_op.ml
test/test_markdown.ml

- update `Tag of string` -> `Tag of Inline.t list`
- remove `inline.Block_reference s` type , which is moved to `inline.Link` with `inline.url=Block_ref <id>`
- update `inline.url` type
```ocaml
type url =
| File of string
| Search of string
| Complex of complex
| Page_ref of string  (* new added *)
| Block_ref of string (* new added *)
```
```ocaml
(* before *)
Inline.Block_reference "id"
(* after *)
Inline.Link {url=inline.Block_ref "id"; ...}
```
```ocaml
(*
parse "[[a]]"
*)
(*before*)
Link
{ url = Search "a"
; label = [ Plain "" ]
; title = None
; full_text = "[[a]]"
; metadata = ""
}
(*after*)
Link
{ url = Page_ref "a"
; label = [ Plain "" ]
; title = None
; full_text = "[[a]]"
; metadata = ""
}
(*----------------------
parse "[label]([[aaa]])"
*)
(*before*)
Link
{ url = Search …
```

enhance: update inline link type

---

lib/prelude.ml

decrease `direct_depth_append_` & `direct_depth_filter_` in Prelude.List

fix: stackoverflow when export md

---

bench/bench.ml
bin/main.ml
js/lib.ml
lib/export/conf.ml
lib/export/markdown.ml
lib/export/opml.ml
lib/transform/markdown_transformer.ml
test/dune
test/gen_md_files.ml
test/test_export_markdown.ml
test/test_export_opml.ml
test/test_markdown.ml
test/test_org.ml

also remove `conf.ignore_heading_list_marker` option

fix(opml): remove prefix spaces of text of exported opml

---

bench/bench.ml
bin/main.ml
lib/export/conf.ml
lib/export/markdown.ml
lib/export/opml.ml
lib/syntax/tree_type.ml
lib/syntax/tree_type.mli
lib/transform/markdown_transformer.ml
test/gen_md_files.ml
test/test_export_markdown.ml
test/test_export_opml.ml
test/test_markdown.ml
test/test_org.ml

- remove page-ref , [[text]] -> text
- remove emphasis, `**text**` -> text, `__text__` -> text, and so on

feat: add remove meta-chars options when exporting

---

lib/mldoc_parser.ml
lib/parsers.ml
lib/syntax/inline.ml
lib/syntax/type_op.ml
test/test_markdown.ml

Fixed:
- emphasis :
- `*a\*b\**` -> ![image](https://user-images.githubusercontent.com/5608710/128755717-faf2d70e-a1af-4a9f-a918-0b38a75f1ade.png)
- `_a\_ a_` -> ![image](https://user-images.githubusercontent.com/5608710/128755782-dbcb1995-012a-49c0-a8b5-a0eea9dc8adf.png)
- quote
- `\> dede` -> ![image](https://user-images.githubusercontent.com/5608710/128755959-70386203-2504-4fd0-8cca-249cd9dc76dc.png)
- link
- `[lab\]el](ur\)l)` ->![image](https://user-images.githubusercontent.com/5608710/128842889-c9c334e1-a64c-4a01-ae7b-99ea65b051fe.png)
- `[[\]]]` -> ![image](https://user-images.githubusercontent.com/5608710/128842940-94bf7ab7-4fce-4358-9fd0-38c4d12beb38.png)
TODO:
- ~fix unescape chars in inline.link~
- exported md should escape meta chars (will support this in another PR)

fix(md): unescaped char in emphasis

---

lib/syntax/inline.ml
test/test_markdown.ml

fix issue https://github.com/logseq/logseq/issues/2622
|link | before| after|
|----|---|--|
|`[a][b](c)`|![image](https://user-images.githubusercontent.com/5608710/129823194-fbfad548-d20a-489c-baa2-6b3bf40935e5.png)|![image](https://user-images.githubusercontent.com/5608710/129823252-2d97c0df-cfb1-45a6-8137-edf806e0bff8.png)|

fix(md): link label

---

js/lib.ml
lib/export/markdown.ml
lib/prelude.ml
lib/syntax/drawer.ml
lib/syntax/inline.ml
test/test_markdown.ml

`{{macro "a,r,g1", arg2}}` -> macro name: macro, macro args: ["\\"a,r,g1\\"", "arg2"]

enhance: macro arg support arg in " pair, escape from sep-by comma

---

lib/export/html.ml

|md|html(before)|html(after)|
|--|--|--|
|[[title]]|`<li><a href="title"></a></li>`|`<li>title</li>`|

fix: html-export page-ref

---

lib/export/html.ml
lib/export/markdown.ml
test/test_export_markdown.ml

replace `{{cloze content}}` with `content` when exporting

feat(export): replace cloze macro with its content

---

lib/syntax/inline.ml
test/test_markdown.ml
test/test_org.ml

1. md page-ref contains (: | ://) should be parsed to a normal
page-ref instead a link
2. org-link is not supported in md anymore

fix(md): page-ref contains colon

---

dune-project
mldoc.opam

Hello,
When I tried `opam pin add mldoc ~/github/mldoc --working-dir` I got errors about dune project and opam dependencies (`angstrom` and `xmlm`). This patch fixes my issues.

Some fixes to dune project and .ocaml file

---

bench/bench.ml
bench/dune

Need to change Command.run due to new API.
Documentation link: https://ocaml.org/p/core_unix/v0.14.0/doc/Command_unix/index.html#val-run

Update deprecated Command.run

---

lib/syntax/inline.ml
test/test_markdown.ml

This aims to address a long-standing gripe I have when using Logseq!
In Emacs's `org-mode`, `{}` can be used to separate items like `\Delta` from any text that follows. This is consistent with how `{}` is used to explicitly mark where sub/superscripts end. Here are some examples from Emacs that I've converted into test cases:
This:
Becomes:
One way I've continued to deviate from this Emacs behavior is by transforming `\DeltaG` into `DeltaG` (without the backslash). This keeps the same behavior that already existed and seems to fit a bit better with the way Logseq displays things?
I'm happy to change that too!
(Also, sorry if I'm made some simple mistakes in this short PR, today is the first time I've ever read / written OCaml code and I'm working off of a familiarity with Haskell!)

fix: inline entity separators

---

js/package/bin/convert.cmd.js

- fix: `stdout` cannot be used as output
- fix: read from `stdin` doesn't work
- fix: `html` output format cannot be used
- fix: arg `append` is not a boolean type
+ feat: added `-f`, `-format` param → output format can be different than extension
+ feat: added `ast` output format
+ feat: added `-with-pos` option to include positions meta info

AST output format; new configuration options & fix some bugs
